resource_group_name  = "cmaz-a36a106e-mod3-rg"
storage_account_name = "cmaza36a106esa"
vnet_name            = "cmaz-a36a106e-mod3-vnet"
subnet_front         = "frontend"
subnet_back          = "backend"
creator              = "tymur_nikolaiev@epam.com"
